version: "3.7"
services:
  django:
    build:
      context: ./src
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env

  db:
    image: postgres:13.2-alpine
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    name: family-budget-db-data
